### ISSUE TITLE
install-consul, install-dnsmasq, and run-consul are not Terraform modules

### ISSUE THREAD

**Issue by rberlind** [hashicorp/terraform-azurerm-consul#11]
It doesn't really make sense that the install-consul, install-dnsmasq, and run-consul directories are under the modules directory since none of them contain Terraform modules.  In contrast, the consul-cluster and consul-security-group-rules directories DO contain Terraform modules.

**Comment by mcalhoun** [comment]
Hi @rberlind. We package sub-modules (whether Terraform, bash, golang, etc.) under the module directory. These are, in fact, sub-modules even though they aren't Terraform code.

**Comment by rberlind** [comment]
I think you're violating the convention described under https://www.terraform.io/docs/modules/create.html#standard-module-structure

That being said, I don't really know that HashiCorp has a convention on where scripts like the ones you've included should go. It might make sense to add a scripts directory.  I will suggest that we modify that doc to suggest that.
